when:
  event:
    - push

steps:
  deploy:
    image: alpine:latest

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/sasmeka/projects/water_monitoring:/app

    commands:
      - apk add --no-cache git docker-cli docker-cli-compose

      - cd /app

      - |
        if [ ! -d ".git" ]; then
          echo "Repository belum ada, cloning..."
          rm -rf ./*
          git clone https://github.com/sasmeka/water_monitoring.git .
        else
          echo "Repository sudah ada, pulling..."
          git reset --hard
          git pull
        fi

      - docker compose -p water_monitoring up -d --build --remove-orphans
      - docker image prune -f
